# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainapp3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1159, 882)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setBaseSize(QtCore.QSize(1000, 800))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("QTIcons/Laser2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QtCore.QSize(18, 18))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1141, 861))
        self.tabWidget.setToolTip("")
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 8pt \"Eras Medium ITC\";\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_16 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(0, 30, 1131, 758))
        self.gridLayoutWidget_16.setObjectName("gridLayoutWidget_16")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gridLayoutWidget_16)
        self.gridLayout_16.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_68 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_68.setMinimumSize(QtCore.QSize(400, 0))
        self.label_68.setMaximumSize(QtCore.QSize(800, 300))
        self.label_68.setBaseSize(QtCore.QSize(400, 300))
        self.label_68.setText("")
        self.label_68.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/ProgramFlow.png"))
        self.label_68.setScaledContents(True)
        self.label_68.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_68.setObjectName("label_68")
        self.gridLayout_16.addWidget(self.label_68, 3, 0, 5, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.gridLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(0, 200))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(10000, 10000))
        self.textBrowser_3.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_16.addWidget(self.textBrowser_3, 1, 0, 1, 4, QtCore.Qt.AlignVCenter)
        self.commandLinkButton_6 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_16)
        self.commandLinkButton_6.setMaximumSize(QtCore.QSize(200, 80))
        self.commandLinkButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.commandLinkButton_6.setStyleSheet("font: 16pt \"Eras Bold ITC\";\n"
"background-color: rgb(0, 153, 255,50);\n"
"color: rgb(0, 170, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/QTIcons/RunArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_6.setIcon(icon1)
        self.commandLinkButton_6.setIconSize(QtCore.QSize(40, 40))
        self.commandLinkButton_6.setCheckable(False)
        self.commandLinkButton_6.setObjectName("commandLinkButton_6")
        self.gridLayout_16.addWidget(self.commandLinkButton_6, 4, 3, 4, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.gridLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_17.sizePolicy().hasHeightForWidth())
        self.textBrowser_17.setSizePolicy(sizePolicy)
        self.textBrowser_17.setMaximumSize(QtCore.QSize(16777215, 80))
        self.textBrowser_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.gridLayout_16.addWidget(self.textBrowser_17, 2, 0, 1, 4)
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(400, 100))
        self.textBrowser.setMaximumSize(QtCore.QSize(800, 100))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_16.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.label_172 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_172.setMaximumSize(QtCore.QSize(250, 80))
        self.label_172.setText("")
        self.label_172.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/Py2Pulse Logo.PNG"))
        self.label_172.setScaledContents(True)
        self.label_172.setObjectName("label_172")
        self.gridLayout_16.addWidget(self.label_172, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.label_69 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_69.sizePolicy().hasHeightForWidth())
        self.label_69.setSizePolicy(sizePolicy)
        self.label_69.setMinimumSize(QtCore.QSize(400, 0))
        self.label_69.setMaximumSize(QtCore.QSize(800, 220))
        self.label_69.setBaseSize(QtCore.QSize(400, 200))
        self.label_69.setText("")
        self.label_69.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/ProgramFlow2.png"))
        self.label_69.setScaledContents(True)
        self.label_69.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_69.setObjectName("label_69")
        self.gridLayout_16.addWidget(self.label_69, 3, 1, 1, 3)
        self.commandLinkButton_7 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_16)
        self.commandLinkButton_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.commandLinkButton_7.setToolTipDuration(0)
        self.commandLinkButton_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.commandLinkButton_7.setStyleSheet("font: 10pt \"Eras Medium ITC\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/QTIcons/InfoDark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_7.setIcon(icon2)
        self.commandLinkButton_7.setIconSize(QtCore.QSize(30, 20))
        self.commandLinkButton_7.setObjectName("commandLinkButton_7")
        self.gridLayout_16.addWidget(self.commandLinkButton_7, 4, 1, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setStyleSheet("font: 8pt \"Eras Light ITC\";")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_16.addWidget(self.checkBox, 5, 1, 3, 2)
        self.textBrowser.raise_()
        self.textBrowser_3.raise_()
        self.textBrowser_17.raise_()
        self.label_69.raise_()
        self.label_68.raise_()
        self.checkBox.raise_()
        self.commandLinkButton_6.raise_()
        self.commandLinkButton_7.raise_()
        self.label_172.raise_()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("QTIcons/Home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(10, 10, 1102, 801))
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_148 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_148.setMaximumSize(QtCore.QSize(40, 40))
        self.label_148.setText("")
        self.label_148.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/Folder.png"))
        self.label_148.setScaledContents(True)
        self.label_148.setObjectName("label_148")
        self.gridLayout_15.addWidget(self.label_148, 7, 0, 1, 1)
        self.label_149 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_149.setMaximumSize(QtCore.QSize(1000, 500))
        self.label_149.setText("")
        self.label_149.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/FolderOrg.png"))
        self.label_149.setScaledContents(True)
        self.label_149.setObjectName("label_149")
        self.gridLayout_15.addWidget(self.label_149, 3, 0, 1, 7, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_171 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_171.setMaximumSize(QtCore.QSize(180, 60))
        self.label_171.setText("")
        self.label_171.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/Py2Pulse Logo.PNG"))
        self.label_171.setScaledContents(True)
        self.label_171.setObjectName("label_171")
        self.gridLayout_15.addWidget(self.label_171, 0, 6, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.gridLayoutWidget_15)
        self.textBrowser_18.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textBrowser_18.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.textBrowser_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.gridLayout_15.addWidget(self.textBrowser_18, 1, 0, 1, 7, QtCore.Qt.AlignVCenter)
        self.textBrowser_43 = QtWidgets.QTextBrowser(self.gridLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_43.sizePolicy().hasHeightForWidth())
        self.textBrowser_43.setSizePolicy(sizePolicy)
        self.textBrowser_43.setMaximumSize(QtCore.QSize(700, 50))
        self.textBrowser_43.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_43.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_43.setObjectName("textBrowser_43")
        self.gridLayout_15.addWidget(self.textBrowser_43, 6, 0, 1, 5)
        self.textBrowser_47 = QtWidgets.QTextBrowser(self.gridLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_47.sizePolicy().hasHeightForWidth())
        self.textBrowser_47.setSizePolicy(sizePolicy)
        self.textBrowser_47.setMaximumSize(QtCore.QSize(700, 50))
        self.textBrowser_47.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_47.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_47.setObjectName("textBrowser_47")
        self.gridLayout_15.addWidget(self.textBrowser_47, 8, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem, 5, 0, 1, 7)
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.gridLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_19.sizePolicy().hasHeightForWidth())
        self.textBrowser_19.setSizePolicy(sizePolicy)
        self.textBrowser_19.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.gridLayout_15.addWidget(self.textBrowser_19, 0, 0, 1, 6)
        self.toolButton_2 = QtWidgets.QToolButton(self.gridLayoutWidget_15)
        self.toolButton_2.setStyleSheet("font: 12pt \"Eras Medium ITC\";")
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_15.addWidget(self.toolButton_2, 7, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.gridLayoutWidget_15)
        self.toolButton.setStyleSheet("font: 12pt \"Eras Medium ITC\";")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_15.addWidget(self.toolButton, 9, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem1, 10, 0, 1, 5)
        self.commandLinkButton_10 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_15)
        self.commandLinkButton_10.setMaximumSize(QtCore.QSize(200, 80))
        self.commandLinkButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.commandLinkButton_10.setStyleSheet("font: 16pt \"Eras Bold ITC\";\n"
"background-color: rgb(0, 153, 255,50);\n"
"color: rgb(0, 170, 0);")
        self.commandLinkButton_10.setIcon(icon1)
        self.commandLinkButton_10.setIconSize(QtCore.QSize(40, 40))
        self.commandLinkButton_10.setCheckable(False)
        self.commandLinkButton_10.setObjectName("commandLinkButton_10")
        self.gridLayout_15.addWidget(self.commandLinkButton_10, 10, 6, 1, 1)
        self.label_150 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_150.setMaximumSize(QtCore.QSize(40, 40))
        self.label_150.setText("")
        self.label_150.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/Folder.png"))
        self.label_150.setScaledContents(True)
        self.label_150.setObjectName("label_150")
        self.gridLayout_15.addWidget(self.label_150, 9, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem2, 2, 0, 1, 7)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/QTIcons/Setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_6, icon4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_6.setGeometry(QtCore.QRect(0, 140, 421, 661))
        self.textBrowser_6.setStyleSheet("background-color: rgba(17, 53, 196, 50);")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.gridLayoutWidget_14 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(0, 0, 1111, 801))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_152 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_152.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_152.setObjectName("label_152")
        self.gridLayout.addWidget(self.label_152, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        self.label_153 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_153.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_153.setObjectName("label_153")
        self.gridLayout.addWidget(self.label_153, 2, 0, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout.addWidget(self.lineEdit_27, 2, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_60.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 2, 2, 1, 1)
        self.label_151 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_151.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_151.setObjectName("label_151")
        self.gridLayout.addWidget(self.label_151, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_3.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 3, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_3, 3, 2, 1, 1)
        self.textBrowser_50 = QtWidgets.QTextBrowser(self.gridLayoutWidget_14)
        self.textBrowser_50.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_50.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_50.setObjectName("textBrowser_50")
        self.gridLayout_14.addWidget(self.textBrowser_50, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_21.setMaximumSize(QtCore.QSize(250, 200))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("QTIcons/CalibrationSampleOutput.PNG"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_14.addWidget(self.label_21, 3, 4, 1, 1)
        self.textBrowser_48 = QtWidgets.QTextBrowser(self.gridLayoutWidget_14)
        self.textBrowser_48.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser_48.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_48.setObjectName("textBrowser_48")
        self.gridLayout_14.addWidget(self.textBrowser_48, 0, 0, 1, 4)
        self.textBrowser_52 = QtWidgets.QTextBrowser(self.gridLayoutWidget_14)
        self.textBrowser_52.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_52.setObjectName("textBrowser_52")
        self.gridLayout_14.addWidget(self.textBrowser_52, 2, 2, 1, 2)
        self.label_173 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_173.setMaximumSize(QtCore.QSize(180, 60))
        self.label_173.setText("")
        self.label_173.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/Py2Pulse Logo.PNG"))
        self.label_173.setScaledContents(True)
        self.label_173.setObjectName("label_173")
        self.gridLayout_14.addWidget(self.label_173, 0, 4, 1, 1)
        self.textBrowser_53 = QtWidgets.QTextBrowser(self.gridLayoutWidget_14)
        self.textBrowser_53.setMaximumSize(QtCore.QSize(250, 16777215))
        self.textBrowser_53.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_53.setObjectName("textBrowser_53")
        self.gridLayout_14.addWidget(self.textBrowser_53, 2, 4, 1, 1)
        self.textBrowser_49 = QtWidgets.QTextBrowser(self.gridLayoutWidget_14)
        self.textBrowser_49.setMaximumSize(QtCore.QSize(16777215, 400))
        self.textBrowser_49.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.textBrowser_49.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_49.setObjectName("textBrowser_49")
        self.gridLayout_14.addWidget(self.textBrowser_49, 1, 0, 1, 5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_57.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_57.setText("")
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_2.addWidget(self.lineEdit_57, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_2.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_3.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 5, 1, 1, 1)
        self.textBrowser_51 = QtWidgets.QTextBrowser(self.gridLayoutWidget_14)
        self.textBrowser_51.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_51.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_51.setObjectName("textBrowser_51")
        self.gridLayout_2.addWidget(self.textBrowser_51, 1, 0, 1, 3)
        self.gridLayout_14.addLayout(self.gridLayout_2, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem3, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem4, 3, 1, 1, 1)
        self.commandLinkButton_8 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_14)
        self.commandLinkButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_8.setStyleSheet("font: 14pt \"Eras Bold ITC\";\n"
"background-color: rgb(0, 153, 255,50);\n"
"color: rgb(0, 170, 0);")
        self.commandLinkButton_8.setIcon(icon1)
        self.commandLinkButton_8.setCheckable(False)
        self.commandLinkButton_8.setObjectName("commandLinkButton_8")
        self.gridLayout_14.addWidget(self.commandLinkButton_8, 4, 4, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_14)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("font: 10pt \"Eras Bold ITC\";\n"
"selection-color: rgb(54, 54, 54);\n"
"border-color: rgb(17, 53, 196);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_14.addWidget(self.pushButton_6, 4, 2, 1, 1)
        self.textBrowser_50.raise_()
        self.textBrowser_48.raise_()
        self.textBrowser_49.raise_()
        self.textBrowser_52.raise_()
        self.label_173.raise_()
        self.textBrowser_53.raise_()
        self.label_21.raise_()
        self.commandLinkButton_8.raise_()
        self.pushButton_6.raise_()
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_5.setGeometry(QtCore.QRect(440, 130, 411, 671))
        self.textBrowser_5.setStyleSheet("background-color: rgba(17, 53, 196, 50);")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_5.raise_()
        self.textBrowser_6.raise_()
        self.gridLayoutWidget_14.raise_()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("QTIcons/Lightning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(230, 170, 141, 16))
        self.label_23.setObjectName("label_23")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_7.setGeometry(QtCore.QRect(0, 130, 201, 231))
        self.textBrowser_7.setStyleSheet("background-color: rgba(17, 53, 196, 50);")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 170, 201, 67))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_4.addWidget(self.lineEdit_29, 0, 1, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_4.addWidget(self.lineEdit_30, 1, 1, 1, 1)
        self.label_162 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_162.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_162.setObjectName("label_162")
        self.gridLayout_4.addWidget(self.label_162, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 2, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_4.addWidget(self.lineEdit_31, 2, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_77.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_77.setObjectName("label_77")
        self.gridLayout_4.addWidget(self.label_77, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_163 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_163.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_163.setObjectName("label_163")
        self.gridLayout_4.addWidget(self.label_163, 2, 0, 1, 1)
        self.label_164 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_164.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_164.setObjectName("label_164")
        self.gridLayout_4.addWidget(self.label_164, 0, 0, 1, 1)
        self.textBrowser_64 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_64.setGeometry(QtCore.QRect(0, 130, 201, 41))
        self.textBrowser_64.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_64.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_64.setObjectName("textBrowser_64")
        self.textBrowser_65 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_65.setGeometry(QtCore.QRect(0, 240, 201, 31))
        self.textBrowser_65.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_65.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_65.setObjectName("textBrowser_65")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 270, 201, 90))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_58.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_58.setText("")
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout_5.addWidget(self.lineEdit_58, 1, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_78.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_78.setObjectName("label_78")
        self.gridLayout_5.addWidget(self.label_78, 1, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_4.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_5.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_79.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_79.setWordWrap(True)
        self.label_79.setObjectName("label_79")
        self.gridLayout_5.addWidget(self.label_79, 0, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_80.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_80.setObjectName("label_80")
        self.gridLayout_5.addWidget(self.label_80, 1, 0, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_32.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_32.setText("")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_5.addWidget(self.lineEdit_32, 0, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_81.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_81.setObjectName("label_81")
        self.gridLayout_5.addWidget(self.label_81, 0, 2, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_82.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_82.setWordWrap(True)
        self.label_82.setObjectName("label_82")
        self.gridLayout_5.addWidget(self.label_82, 3, 0, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_33.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_33.setText("")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_5.addWidget(self.lineEdit_33, 3, 1, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(230, 190, 161, 90))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_24.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_131 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_131.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_131.setObjectName("label_131")
        self.gridLayout_7.addWidget(self.label_131, 1, 2, 1, 1)
        self.label_132 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_132.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_132.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_132.setWordWrap(True)
        self.label_132.setObjectName("label_132")
        self.gridLayout_7.addWidget(self.label_132, 0, 0, 1, 1)
        self.label_133 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_133.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_133.setObjectName("label_133")
        self.gridLayout_7.addWidget(self.label_133, 1, 0, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_55.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_55.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_55.setText("")
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_7.addWidget(self.lineEdit_55, 0, 1, 1, 1)
        self.label_134 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_134.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_134.setObjectName("label_134")
        self.gridLayout_7.addWidget(self.label_134, 0, 2, 1, 1)
        self.label_135 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_135.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_135.setWordWrap(True)
        self.label_135.setObjectName("label_135")
        self.gridLayout_7.addWidget(self.label_135, 3, 0, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_56.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_56.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_56.setText("")
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_7.addWidget(self.lineEdit_56, 1, 1, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_59.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_59.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_59.setText("")
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_7.addWidget(self.lineEdit_59, 2, 1, 1, 1)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_60.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_60.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_60.setText("")
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout_7.addWidget(self.lineEdit_60, 3, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(240, 320, 141, 31))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("font: 10pt \"Eras Bold ITC\";\n"
"selection-color: rgb(54, 54, 54);\n"
"border-color: rgb(17, 53, 196);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.textBrowser_33 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_33.setGeometry(QtCore.QRect(210, 130, 201, 231))
        self.textBrowser_33.setStyleSheet("background-color: rgba(17, 53, 196, 50);")
        self.textBrowser_33.setObjectName("textBrowser_33")
        self.textBrowser_54 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_54.setGeometry(QtCore.QRect(410, 130, 201, 41))
        self.textBrowser_54.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_54.setObjectName("textBrowser_54")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(430, 160, 161, 101))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("QTIcons/CalibrationSampleOutput.PNG"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.commandLinkButton_9 = QtWidgets.QCommandLinkButton(self.tab_3)
        self.commandLinkButton_9.setGeometry(QtCore.QRect(470, 320, 91, 31))
        self.commandLinkButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_9.setStyleSheet("font: 14pt \"Eras Bold ITC\";\n"
"background-color: rgb(0, 153, 255,50);\n"
"color: rgb(0, 170, 0);")
        self.commandLinkButton_9.setIcon(icon1)
        self.commandLinkButton_9.setCheckable(False)
        self.commandLinkButton_9.setObjectName("commandLinkButton_9")
        self.textBrowser_55 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_55.setGeometry(QtCore.QRect(210, 130, 201, 41))
        self.textBrowser_55.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_55.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_55.setObjectName("textBrowser_55")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(0, 0, 611, 121))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_169 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_169.setMaximumSize(QtCore.QSize(90, 25))
        self.label_169.setText("")
        self.label_169.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/Py2Pulse Logo.PNG"))
        self.label_169.setScaledContents(True)
        self.label_169.setObjectName("label_169")
        self.gridLayout_13.addWidget(self.label_169, 0, 1, 1, 1)
        self.textBrowser_62 = QtWidgets.QTextBrowser(self.gridLayoutWidget_13)
        self.textBrowser_62.setMaximumSize(QtCore.QSize(16777215, 36))
        self.textBrowser_62.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_62.setObjectName("textBrowser_62")
        self.gridLayout_13.addWidget(self.textBrowser_62, 0, 0, 1, 1)
        self.textBrowser_63 = QtWidgets.QTextBrowser(self.gridLayoutWidget_13)
        self.textBrowser_63.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.textBrowser_63.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_63.setObjectName("textBrowser_63")
        self.gridLayout_13.addWidget(self.textBrowser_63, 1, 0, 1, 2)
        self.textBrowser_33.raise_()
        self.textBrowser_7.raise_()
        self.label_23.raise_()
        self.gridLayoutWidget_4.raise_()
        self.textBrowser_64.raise_()
        self.textBrowser_65.raise_()
        self.gridLayoutWidget_5.raise_()
        self.gridLayoutWidget_7.raise_()
        self.pushButton_9.raise_()
        self.textBrowser_54.raise_()
        self.label_22.raise_()
        self.commandLinkButton_9.raise_()
        self.textBrowser_55.raise_()
        self.gridLayoutWidget_13.raise_()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("QTIcons/Timing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 290, 201, 90))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_85 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_85.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_85.setObjectName("label_85")
        self.gridLayout_6.addWidget(self.label_85, 1, 0, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_86.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_86.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_86.setObjectName("label_86")
        self.gridLayout_6.addWidget(self.label_86, 0, 2, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_87.setMinimumSize(QtCore.QSize(50, 0))
        self.label_87.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_87.setWordWrap(True)
        self.label_87.setObjectName("label_87")
        self.gridLayout_6.addWidget(self.label_87, 3, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_20.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_83.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_83.setObjectName("label_83")
        self.gridLayout_6.addWidget(self.label_83, 1, 2, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_84.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_84.setWordWrap(True)
        self.label_84.setObjectName("label_84")
        self.gridLayout_6.addWidget(self.label_84, 0, 0, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_34.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_34.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_34.setText("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_6.addWidget(self.lineEdit_34, 0, 1, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_39.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_39.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_39.setText("")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_6.addWidget(self.lineEdit_39, 1, 1, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_40.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_40.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_40.setText("")
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_6.addWidget(self.lineEdit_40, 2, 1, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_41.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_41.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_41.setText("")
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_6.addWidget(self.lineEdit_41, 3, 1, 1, 1)
        self.textBrowser_68 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_68.setGeometry(QtCore.QRect(0, 140, 201, 41))
        self.textBrowser_68.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_68.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_68.setObjectName("textBrowser_68")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(0, 180, 201, 90))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_168 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_168.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_168.setObjectName("label_168")
        self.gridLayout_9.addWidget(self.label_168, 1, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_63.setWordWrap(True)
        self.label_63.setObjectName("label_63")
        self.gridLayout_9.addWidget(self.label_63, 0, 0, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_42.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_42.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_42.setText("")
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_9.addWidget(self.lineEdit_42, 1, 1, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_43.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_43.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_43.setText("")
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_9.addWidget(self.lineEdit_43, 2, 1, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_44.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_44.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_44.setText("")
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_9.addWidget(self.lineEdit_44, 3, 1, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_36.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_36.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_9.addWidget(self.lineEdit_36, 0, 1, 1, 1)
        self.label_166 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_166.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_166.setObjectName("label_166")
        self.gridLayout_9.addWidget(self.label_166, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_26.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_26.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 1, 2, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_88.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_88.setObjectName("label_88")
        self.gridLayout_9.addWidget(self.label_88, 3, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_27.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 2, 2, 1, 1)
        self.label_167 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_167.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_167.setObjectName("label_167")
        self.gridLayout_9.addWidget(self.label_167, 3, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 330, 141, 31))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("font: 10pt \"Eras Bold ITC\";\n"
"selection-color: rgb(54, 54, 54);\n"
"border-color: rgb(17, 53, 196);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.textBrowser_69 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_69.setGeometry(QtCore.QRect(-10, 260, 211, 31))
        self.textBrowser_69.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_69.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_69.setObjectName("textBrowser_69")
        self.textBrowser_34 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_34.setGeometry(QtCore.QRect(0, 140, 201, 231))
        self.textBrowser_34.setStyleSheet("background-color: rgba(17, 53, 196, 50);")
        self.textBrowser_34.setObjectName("textBrowser_34")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(220, 190, 181, 51))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget_10)
        self.radioButton_2.setStyleSheet("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_10.addWidget(self.radioButton_2, 2, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_10)
        self.radioButton.setStyleSheet("")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_10.addWidget(self.radioButton, 1, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_65.setStyleSheet("font: 8pt \"Eras Medium ITC\";")
        self.label_65.setObjectName("label_65")
        self.gridLayout_10.addWidget(self.label_65, 0, 0, 1, 1)
        self.textBrowser_56 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_56.setGeometry(QtCore.QRect(210, 140, 201, 41))
        self.textBrowser_56.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_56.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_56.setObjectName("textBrowser_56")
        self.textBrowser_35 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_35.setGeometry(QtCore.QRect(210, 140, 201, 231))
        self.textBrowser_35.setStyleSheet("background-color: rgba(17, 53, 196, 50);")
        self.textBrowser_35.setObjectName("textBrowser_35")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(220, 260, 181, 60))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget_11)
        self.radioButton_3.setStyleSheet("")
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_11.addWidget(self.radioButton_3, 1, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.gridLayoutWidget_11)
        self.radioButton_4.setStyleSheet("")
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_11.addWidget(self.radioButton_4, 2, 0, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_46.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_46.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout_11.addWidget(self.lineEdit_46, 1, 2, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_45.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_45.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout_11.addWidget(self.lineEdit_45, 1, 1, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_47.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_47.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_11.addWidget(self.lineEdit_47, 1, 3, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_48.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_48.setStyleSheet("font: 6pt \"Eras Light ITC\";\n"
"color: rgb(145, 145, 145);")
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_11.addWidget(self.lineEdit_48, 2, 1, 1, 3)
        self.label_67 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_67.setObjectName("label_67")
        self.gridLayout_11.addWidget(self.label_67, 0, 0, 1, 4)
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(0, 0, 611, 131))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.textBrowser_67 = QtWidgets.QTextBrowser(self.gridLayoutWidget_12)
        self.textBrowser_67.setMaximumSize(QtCore.QSize(500, 36))
        self.textBrowser_67.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_67.setObjectName("textBrowser_67")
        self.gridLayout_12.addWidget(self.textBrowser_67, 0, 0, 1, 1)
        self.label_165 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_165.setMaximumSize(QtCore.QSize(90, 25))
        self.label_165.setText("")
        self.label_165.setPixmap(QtGui.QPixmap(":/Icons/QTIcons/Py2Pulse Logo.PNG"))
        self.label_165.setScaledContents(True)
        self.label_165.setObjectName("label_165")
        self.gridLayout_12.addWidget(self.label_165, 0, 1, 1, 1)
        self.textBrowser_66 = QtWidgets.QTextBrowser(self.gridLayoutWidget_12)
        self.textBrowser_66.setMaximumSize(QtCore.QSize(16777215, 90))
        self.textBrowser_66.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.textBrowser_66.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_66.setObjectName("textBrowser_66")
        self.gridLayout_12.addWidget(self.textBrowser_66, 1, 0, 1, 2)
        self.textBrowser_35.raise_()
        self.textBrowser_34.raise_()
        self.gridLayoutWidget_6.raise_()
        self.textBrowser_68.raise_()
        self.gridLayoutWidget_9.raise_()
        self.pushButton_10.raise_()
        self.textBrowser_69.raise_()
        self.gridLayoutWidget_10.raise_()
        self.textBrowser_56.raise_()
        self.gridLayoutWidget_11.raise_()
        self.gridLayoutWidget_12.raise_()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("QTIcons/microscope.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("QTIcons/results.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon8, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Py2Pulse"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Py2Pulse </span><span style=\" font-size:12pt; color:#ffffff;\">is a program designed to enable scientists to carry out optogenetics experiments using the </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#0099ff;\">Coherent Monaco Industrial Femtosecond Laser</span><span style=\" font-size:12pt; color:#ffffff;\">. </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">It enables the user to vary the laser\'s parameters in the GUI while the Py2Pulse modules written in Python and Arduino build the Hardware Abstraction Layer and deploy the pulses via serial commands. </span></p></body></html>"))
        self.commandLinkButton_6.setText(_translate("MainWindow", "SETUP"))
        self.textBrowser_17.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:16pt; color:#00007f;\">What are the steps?</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:20pt;\">GET STARTED WITH</span></p></body></html>"))
        self.commandLinkButton_7.setText(_translate("MainWindow", "Read Terms of Use"))
        self.checkBox.setText(_translate("MainWindow", "I have read and understood the terms of use"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.textBrowser_18.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">This page aims to set out the organisation of the project folder. The Python script will create subfolders within the main project folder and save the calibration file to the relevant location as shown in the diagram below.</span></p></body></html>"))
        self.textBrowser_43.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:14pt; color:#00007f;\">1. Select your project folder</span></p></body></html>"))
        self.textBrowser_47.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:14pt; color:#00007f;\">2. Upload the calibration file.</span></p></body></html>"))
        self.textBrowser_19.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:24pt;\">                        GET ORGANISED</span></p></body></html>"))
        self.toolButton_2.setText(_translate("MainWindow", "Browse"))
        self.toolButton.setText(_translate("MainWindow", "Browse"))
        self.commandLinkButton_10.setText(_translate("MainWindow", "SETUP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Setup"))
        self.label_9.setText(_translate("MainWindow", "s"))
        self.label_152.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Beam spot diameter:</span></p></body></html>"))
        self.label_153.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Voltage sampling rate:</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "𝜇𝑚"))
        self.label_60.setText(_translate("MainWindow", "Hz"))
        self.label_151.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Calibration ∆t:</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:6pt;\">% of 40 𝜇J</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:6pt;\">% of 40 𝜇J</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Max input energy:</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Samples:</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Min input pulse energy:</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Steps:</p></body></html>"))
        self.textBrowser_50.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:12pt; text-decoration: underline; color:#00007f;\">FIXED PARAMETERS</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#00007f;\">Please insert the laser parameters which will remain the same for each pulse that is deployed.</span></p></body></html>"))
        self.textBrowser_48.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:24pt;\">CALIBRATE THE POWER</span></p></body></html>"))
        self.textBrowser_52.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:12pt; text-decoration: underline; color:#00007f;\">VARIABLE PARAMETERS</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#00007f;\">Please insert the laser parameters which will increase stepwise with each pulse that is deployed.</span></p></body></html>"))
        self.textBrowser_53.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:12pt; text-decoration: underline; color:#00007f;\">OUTPUT PREVIEW</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">This is a simple screenshot of the shape of the expected output.</span></p></body></html>"))
        self.textBrowser_49.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">The power measured by the picker is a non-linear function of the input command pulse energy. This protocol sends serial commands to the laser given user-specified laser parameters, ramping up from the minimum to maximum pulse energy with each pulse at a fixed repetition rate. The laser power and timing is measured by a power meter with an analog output read by the electrophysiology data acquisition board. The protocol returns the Picker power versus inputted command pulse energy.  </span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "fs"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Repetition rate divisor:</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Amplifier repetition rate: (MRR)</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Pulse width 𝜏<span style=\" vertical-align:sub;\">𝑝</span>:</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">No. of pulses per microburst:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "kHz"))
        self.textBrowser_51.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#00007f;\">Consult the </span><span style=\" font-size:7pt; color:#0099ff;\">Coherent Monaco GUI </span><span style=\" font-size:7pt; color:#00007f;\">for the allowable combinations of the following:</span></p></body></html>"))
        self.commandLinkButton_8.setText(_translate("MainWindow", "RUN"))
        self.pushButton_6.setText(_translate("MainWindow", "SET PARAMETERS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Power Calibration"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#00007f;\">* MRR = Amplifier repetition rate</span></p></body></html>"))
        self.label_162.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Beam spot diameter:</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "s"))
        self.label_77.setText(_translate("MainWindow", "Hz"))
        self.label_13.setText(_translate("MainWindow", "𝜇𝑚"))
        self.label_163.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Voltage sampling rate:</span></p></body></html>"))
        self.label_164.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Calibration ∆t:</span></p></body></html>"))
        self.textBrowser_64.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:12pt; text-decoration: underline; color:#00007f;\">FIXED PARAMETERS</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#00007f;\">Please insert the laser parameters which will remain the same for each pulse that is deployed.</span></p></body></html>"))
        self.textBrowser_65.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#00007f;\">Consult the </span><span style=\" font-size:7pt; color:#0099ff;\">Coherent Monaco GUI </span><span style=\" font-size:7pt; color:#00007f;\">for the allowable combinations of the following:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Repetition rate divisor:</p></body></html>"))
        self.label_78.setText(_translate("MainWindow", "fs"))
        self.label_79.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Amplifier repetition rate: (MRR)</span></p></body></html>"))
        self.label_80.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Pulse width 𝜏<span style=\" vertical-align:sub;\">𝑝</span>:</p></body></html>"))
        self.label_81.setText(_translate("MainWindow", "kHz"))
        self.label_82.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">No. of pulses per microburst:</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Samples:</p></body></html>"))
        self.label_131.setText(_translate("MainWindow", "kHz"))
        self.label_132.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Min MRR:</span></p></body></html>"))
        self.label_133.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Max MRR:</p></body></html>"))
        self.label_134.setText(_translate("MainWindow", "kHz"))
        self.label_135.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Steps:</span></p></body></html>"))
        self.pushButton_9.setText(_translate("MainWindow", "SET PARAMETERS"))
        self.textBrowser_54.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:12pt; text-decoration: underline; color:#00007f;\">OUTPUT PREVIEW</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">This is a simple screenshot of the shape of the expected output.</span></p></body></html>"))
        self.commandLinkButton_9.setText(_translate("MainWindow", "RUN"))
        self.textBrowser_55.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:12pt; text-decoration: underline; color:#00007f;\">VARIABLE PARAMETERS</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#00007f;\">Please insert the laser parameters which will increase stepwise with each pulse that is deployed.</span></p></body></html>"))
        self.textBrowser_62.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:24pt;\">VALIDATE THE TIMING</span></p></body></html>"))
        self.textBrowser_63.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">The amplifier repetition rate requires validation. This protocol sends serial commands to the laser given user-specified laser parameters, ramping up from the minimum to the maximum repetition rate at a fixed input pulse energy. The laser power and timing is measured with a power meter with an analog output read by the electrophysiology data acquisition board. The protocol returns the Picker power versus the inputted pulse energy. </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "MRR Calibration"))
        self.label_85.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Pulse width 𝜏<span style=\" vertical-align:sub;\">𝑝</span>:</p></body></html>"))
        self.label_86.setText(_translate("MainWindow", "kHz"))
        self.label_87.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">No. of pulses per microburst:</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Repetition rate divisor:</p></body></html>"))
        self.label_83.setText(_translate("MainWindow", "fs"))
        self.label_84.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">MRR:</span></p></body></html>"))
        self.textBrowser_68.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:12pt; text-decoration: underline; color:#00007f;\">FIXED PARAMETERS</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#00007f;\">Please insert the laser parameters which will remain the same for each pulse that is deployed.</span></p></body></html>"))
        self.label_168.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Stimulation ∆t:</span></p></body></html>"))
        self.label_63.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#00007f;\">Unique experiment label:</span></p></body></html>"))
        self.lineEdit_36.setText(_translate("MainWindow", "e.g. cell_1"))
        self.label_166.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Beam spot diameter:</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "ms"))
        self.label_88.setText(_translate("MainWindow", "Hz"))
        self.label_27.setText(_translate("MainWindow", "𝜇𝑚"))
        self.label_167.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#00007f;\">Current sampling rate:</span></p></body></html>"))
        self.pushButton_10.setText(_translate("MainWindow", "SET PARAMETERS"))
        self.textBrowser_69.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#00007f;\">Consult the </span><span style=\" font-size:7pt; color:#0099ff;\">Coherent Monaco GUI </span><span style=\" font-size:7pt; color:#00007f;\">for the allowable combinations of the following:</span></p></body></html>"))
        self.radioButton_2.setText(_translate("MainWindow", "Repetition rate (kHz)"))
        self.radioButton.setText(_translate("MainWindow", "Power onto cell (mW)"))
        self.label_65.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:10pt; font-weight:600; color:#00007f;\">Select parameter to vary:</span></p></body></html>"))
        self.textBrowser_56.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:12pt; text-decoration: underline; color:#00007f;\">VARIABLE PARAMETERS</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt; color:#00007f;\">Please insert the laser parameters which will increase stepwise with each pulse that is deployed.</span></p></body></html>"))
        self.radioButton_3.setText(_translate("MainWindow", "Step intervals"))
        self.radioButton_4.setText(_translate("MainWindow", "Custom list"))
        self.lineEdit_46.setText(_translate("MainWindow", "Max"))
        self.lineEdit_45.setText(_translate("MainWindow", "Min"))
        self.lineEdit_47.setText(_translate("MainWindow", "Steps"))
        self.lineEdit_48.setText(_translate("MainWindow", "1;2;3;4.... etc"))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:10pt; font-weight:600; color:#00007f;\">Choose option for values:</span></p></body></html>"))
        self.textBrowser_67.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Eras Bold ITC\'; font-size:24pt;\">MAXIMISE THE CURRENT</span></p></body></html>"))
        self.textBrowser_66.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ffffff;\">This protocol involves two parts. </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Part 1:</span><span style=\" font-size:10pt; color:#ffffff;\"> a CHO cell is photostimulated at a fixed repetition rate and at randomly varied powers. The induced current is measured using the voltage-clamp method and results are recorded by the electrophysiology data acquisition board. Photodamage should not occur. The Michaelis-Menten equation is then fitted to the cell to get the mean 𝐾</span><span style=\" font-size:10pt; color:#ffffff; vertical-align:sub;\">𝐷</span><span style=\" font-size:10pt; color:#ffffff;\">. </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Part 2:</span><span style=\" font-size:10pt; color:#ffffff;\"> the same cell will be photostimulated at random powers and an associated repetition rate which satisfies 𝑓</span><span style=\" font-size:10pt; color:#ffffff; vertical-align:sub;\">𝑝</span><span style=\" font-size:10pt; color:#ffffff;\">=𝑝</span><span style=\" font-size:10pt; color:#ffffff; vertical-align:sub;\">0</span><span style=\" font-size:10pt; color:#ffffff; vertical-align:super;\">2</span><span style=\" font-size:10pt; color:#ffffff;\">/𝐾</span><span style=\" font-size:10pt; color:#ffffff; vertical-align:sub;\">𝐷</span><span style=\" font-size:10pt; color:#ffffff;\"> . This is repeated for a number of cells.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Cell Experiments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Results"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

